- hosts: dev
  vars:
    workspace: /home/ubuntu/PUOrganization
  tasks:
  - name: Pull sources from the repository.
    git: 
      repo: git@github.com:PaidUp/PUOrganization.git
      dest: '{{ workspace }}'
      version: develop
      force: yes

  - name: install node modules
    shell: npm install
    args:
      chdir: '{{ workspace }}'

  - name: NODE | Stop APP
    shell: pm2 stop organization
    args:
      chdir: '{{ workspace }}'
    ignore_errors: yes

  - name: NODE | Start APP
    shell: "webpack && pm2 start deploy/ecosystem-{{env}}.json"
    args:
      chdir: '{{ workspace }}'
 