- hosts: stg
  vars:
    workspace: /var/lib/jenkins/workspace/Stage_PUOrganization
  tasks:
  - name: Pull sources from the repository.
    git: 
      repo: git@github.com:PaidUp/PUOrganization.git
      dest: '{{ workspace }}'
      version: stage
      force: yes

  - name: install node modules
    shell: npm install
    args:
      chdir: '{{ workspace }}'

  - name: copy config file
    copy:
      src: /var/www/config/stage/PUOrganization/stage.js
      dest: '{{ workspace }}/server/config/environment'
      owner: jenkins
      group: jenkins

  - name: NODE | Stop APP
    shell: pm2 stop organization-stg
    args:
      chdir: '{{ workspace }}'
    ignore_errors: yes

  - name: NODE | Start APP
    shell: npm run deploy-stg
    args:
      chdir: '{{ workspace }}'
 